version: '3.9'
services:
  # GitHub home for this project with setup instructions: Caution! This project is not open source, and is not available on GitHub
  # Docker Hub home for this project: https://hub.docker.com/u/turtletank99
  adbtuner:
    image: turtletank99/adbtuner:latest
    container_name: adbtuner
    dns_search: localdomain # Change to the name of your LAN's domain, which is usually local or localdomain
    init: true
    ports:
      - 5592:5592
    volumes:
      - adbtuner_config:/app/.config
    restart: unless-stopped
volumes:
  adbtuner_config: