version: '3.9'
services:
  # GitHub home for this project with setup instructions: Caution! This project is not open source, and is not available on GitHub
  # Docker Hub home for this project: https://hub.docker.com/u/turtletank99
  adbtuner:
    image: turtletank99/adbtuner:${TAG}
    container_name: adbtuner
    dns_search: ${DOMAIN} # Change to the name of your LAN's domain, which is usually local or localdomain
    init: true
    ports:
      - ${HOST_PORT}:5592 # Use the same port number the container is using, or optionally change it if the port is already in use on your host
    volumes:
      - adbtuner:/app/.config
    restart: unless-stopped
volumes:
  adbtuner:
    name: ${HOST_VOLUME}

  # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
