version: '3.0'
services:
  channelwatch:
    # 2025.04.26
    # GitHub home for this project: https://github.com/CoderLuii/ChannelWatch.
    # Docker container home for this project with setup instructions: https://hub.docker.com/r/coderluii/channelwatch.
    image: coderluii/channelwatch:${TAG:-latest}
    container_name: channelwatch
    ports:
      - ${HOST_PORT:-8501}:8501
    volumes:
      - ${HOST_DIR}/channelwatch:/config
    restart: unless-stopped
