version: '3.9'
services:
  # GitHub home for this project: https://github.com/dtankdempse/free-iptv-channels
  # Docker Hub home for this project: https://hub.docker.com/r/dtankdemp/free-iptv-channels
  free-iptv-channels:
    image: dtankdemp/free-iptv-channels:${TAG:-latest}
    container_name: free-iptv-channels
    ports:
      - "${PORT:-4242}:4242"
    environment:
      - TZ=${TIMEZONE:-UTC}
    restart: unless-stopped

    # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
