version: '3.9'
services:
  multichannelview:
    # 2025.07.01
    # Github home for this project: https://github.com/bnhf/multichannelview.
    # Docker container home for this project: https://hub.docker.com/r/bnhf/multichannelview.
    image: bnhf/multichannelview:${TAG} # Add the tag like latest or test to the environment variables below.
    container_name: multichannelview
    #devices:
      #- /dev/dri:/dev/dri # Uncomment this and the line above to use Intel Quicksync hardware acceleration. Plus use h26_qsv as the codec.
    ports:
      - ${HOST_PORT}:5001 # Use the same port number the container is using, or optionally change it if the port is already in use on your host.
    environment:
      - CDVR_HOST=${CDVR_HOST} # Hostname/IP of Channels DVR server.
      - CDVR_PORT=${CDVR_PORT} # Port of Channels DVR server.
      - CODEC=${CODEC} # Use h264_qsv (hardware) or libx264 (software).
    restart: unless-stopped
