version: '3.9'
services:
  # GitHub home for this project: https://github.com/maddox/pluto-for-channels
  # Docker Hub home for this project: https://hub.docker.com/r/jonmaddox/pluto-for-channels
  pluto-for-channels:
    image: jonmaddox/pluto-for-channels:latest
    container_name: pluto-for-channels
    ports:
      - 8184:80
    restart: unless-stopped