version: '3.9'
services:
  # 2024.08.31
  # GitHub home for this project: https://github.com/matthuisman/samsung-tvplus-for-channels
  # Docker Hub home for this project: https://hub.docker.com/r/matthuisman/samsung-tvplus-for-channels
  samsung-tvplus-for-channels:
    image: matthuisman/samsung-tvplus-for-channels:${TAG}
    container_name: samsung-tvplus-for-channels
    ports:
      - ${HOST_PORT}:80 # Use the same port number the container is using, or optionally change it if the port is already in use on your host
    environment:
      - REGIONS=${REGIONS} # Comma separated list of regions to use. us,kr,it,in,gb,fr,es,de,ch,ca,at or all supported.
      - TZ=${TZ} # Add your local timezone in standard linux format. E.G. US/Eastern, US/Central, US/Mountain, US/Pacific, etc
    restart: unless-stopped

  # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
  