version: '3.9'
services:
  # GitHub home for this project: https://github.com/matthuisman/samsung-tvplus-for-channels
  # Docker Hub home for this project: https://hub.docker.com/r/matthuisman/samsung-tvplus-for-channels
  samsung-tvplus-for-channels:
    image: matthuisman/samsung-tvplus-for-channels:latest
    container_name: samsung-tvplus-for-channels
    ports:
      - 8182:80
    restart: unless-stopped