version: '3.9'
services:
  # GitHub home for this project with setup instructions: https://github.com/robbiet480/stirr-for-channels
  # Docker Hub home for this project: https://hub.docker.com/r/robbiet480/stirr-for-channels
  stirr-for-channels:
    image: robbiet480/stirr-for-channels:latest
    container_name: stirr-for-channels
    ports:
      - 8181:80
    restart: unless-stopped