version: '3.9'
services:
  vlc-bridge-uk:
    image: registry.gitlab.com/miibeez/vlc-bridge-uk:${TAG}
    container_name: vlc-bridge-uk
    ports:
      - ${HOST_PORT}:7777
    environment:
      - ITV_USER=${ITV_USER}
      - ITV_PASS=${ITV_PASS}
    restart: unless-stopped

  # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
