services:
  vlc-bridge-uk: # This docker-compose typically requires no editing. Use the Environment variables section of Portainer to set your values.
    # 2026.08.31
    # GitLab home for this project: https://gitlab.com/miibeez/vlc-bridge-uk
    # Docker container home for this project: https://gitlab.com/miibeez/vlc-bridge-uk/container_registry
    image: registry.gitlab.com/miibeez/vlc-bridge-uk:${TAG:-latest}
    container_name: vlc-bridge-uk
    ports:
      - ${HOST_PORT}:7777
    environment:
      - ITV_USER=${ITV_USER}
      - ITV_PASS=${ITV_PASS}
    restart: unless-stopped

# A sample set of Environment variables can be found below -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode.
