version: '3.9'
services:
  vlc-bridge-pbs:
    image: registry.gitlab.com/miibeez/vlc-bridge-pbs:${TAG}
    container_name: vlc-bridge-pbs
    ports:
      - ${HOST_PORT}:7777
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
