version: '3.9'
services:
  vlc-bridge-fubo:
    image: jgomez177/vlc-bridge-fubo:${TAG}
    container_name: vlc-bridge-fubo
    ports:
      - ${HOST_PORT}:7777 # Use the same port number the container is using, or optionally change it if the port is already in use on your host
    environment:
      - FUBO_USER=${FUBO_USER}
      - FUBO_PASS=${FUBO_PASS}
    volumes:
      - vlc-bridge-fubo:/app/Config
    restart: unless-stopped
volumes:
  vlc-bridge-fubo:
    name: ${HOST_VOLUME} # This project will store its data in /var/lib/docker/volumes/${HOST_VOLUME}. <project-name_config> is a good name choice.

  # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
