services:
  vlc-bridge-pbs: # This docker-compose typically requires no editing. Use the Environment variables section of Portainer to set your values.
    # 2026.08.31
    # GitLab home for this project: https://gitlab.com/miibeez/vlc-bridge-pbs
    # Docker container home for this project: https://gitlab.com/miibeez/vlc-bridge-pbs/container_registry
    image: registry.gitlab.com/miibeez/vlc-bridge-pbs:${TAG:-latest}
    container_name: vlc-bridge-pbs
    ports:
      - ${HOST_PORT}:7777
    environment:
      - TZ=${TZ}
    restart: unless-stopped

# A sample set of Environment variables can be found below -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode.
