version: '3.9'
services:
  vlc-bridge-fubo:
    image: jgomez177/vlc-bridge-fubo
    container_name: vlc-bridge-fubo
    ports:
      - 7777:7777
    environment:
      - FUBO_USER=${FUBO_USER}
      - FUBO_PASS=${FUBO_PASS}
    restart: unless-stopped
