services:
  watchtower:
    image: nickfedor/watchtower:${TAG:-latest}
    container_name: watchtower
    environment:
      - PATH=${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE:-true}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    # Default Environment variables can be found below under stderr -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode
