services:
  watchtower: # This docker-compose typically requires no editing. Use the Environment variables section of Portainer to set your values.
    # 2026.08.31
    # GitHub home for this project: https://github.com/nicholas-fedor/watchtower
    # Docker Hub home for this project: https://hub.docker.com/r/nickfedor/watchtower
    image: nickfedor/watchtower:${TAG:-latest}
    container_name: watchtower
    environment:
      - PATH=${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE:-true}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# A sample set of Environment variables can be found below -- copy and paste into Portainer-Stacks Environment variables section in Advanced mode.
